# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Live project documentation
author: First Key Homes

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ou-dgolitsyn/react-typescript-styleguide  # Online location of your book  
  branch: dev  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  recursive_update: true
  config: 
    html_static_path: ["../theme"]
    html_css_files: ["style.css"]
    html_theme_options:   
      search_bar_text: "Search the docs..."
      toc_title: "In this article"
      show_navbar_depth: 0
      extra_navbar: "<script type=\"module\" src=\"https://unpkg.com/dark-mode-toggle\"></script>      
      <span class=\"buttons-container\">      
        <button onclick=\"toggleFullScreen()\" class=\"headerbtn\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"\" data-original-title=\"Fullscreen mode\">
        <span class=\"headerbtn__icon-container\">
          <i class=\"fas fa-expand\"></i>
          </span>
        </button>
        <form action=\"https://github.com/ou-dgolitsyn/react-typescript-styleguide\">
            <button class=\"headerbtn menu-dropdown__trigger\" aria-label=\"Source repositories\">
              <i class=\"fab fa-github\"></i>
          </button>
        </form>                
      </span>
      <div>Powered by <a href=\"https://jupyterbook.org\">Jupyter Book</a></div>
      "    
      # <dark-mode-toggle id=\"dark-mode-toggle-1\" appearance=\"toggle\" light=\"Light theme\" dark=\"Dark theme\" permanent=true ></dark-mode-toggle>
      repository_url: "https://github.com/ou-dgolitsyn/react-typescript-styleguide/docs"

   
